apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-from-other-ns
spec:
  rules:
  - name: deny-from-other-ns
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - default
          - kube-public
          - kyverno
          - cert-manager
          - chartmuseum
          - default
          - epinio
          - kube-node-lease
          - kube-public
          - kube-system
          - kyverno
          - traefik
          - workspace
    generate:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      name: deny-from-other-ns
      namespace: "{{request.object.metadata.name}}"
      data:  
        spec:
          podSelector:
            matchLabels:
          ingress:
            - from:
              - podSelector: {}
