apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-resource-request
spec:
  rules:
    - name: set-resrouce-request
      match:
        any:
        - resources:
            kinds:
            - Deployment
            selector:
              matchLabels:
                app.kubernetes.io/managed-by: epinio
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                containers:
                  - (name): "*"
                    resources:
                      requests:
                        +(memory): "100Mi"
                        +(cpu): "100m"